title: Junif F. Fajilagutan Jr.
logo: ![JUNIF ID PIC](https://github.com/user-attachments/assets/8f1d1e75-47fa-4c23-83b6-14806243fabf)
description: Electrical Engineer (REE)
show_download: true
there: jekyll-theme-minimal
